[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIZaSyAxgxxzWDI1Axk_E5tiaQaejrp3wseqXHk"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "classroom-finder-32759.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "classroom-finder-32759"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "classroom-finder-32759.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "577330489518"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:577330489518:web:466bee93adf50ec1d5253f"

[[plugins]]
  package = "@netlify/plugin-nextjs"
